tron:
  config:
    tronDomainUlr: https://api.shasta.trongrid.io
    tronDomainOnline: false
    trc20Address: TAgaqV6dV6Fevud6CZGDFoie7P6NAoujHo
    trc20Decimals: 1000000
    hexPrivateKey: e088f372ffaf11b33900e5fd369abdc64c4819386436541347bb4d9af17dd708
    ownerAddress: TA7weEqvrbyMygQmbNbFuAi2ndEBUAp45h